### ISSUE TITLE
Week 05 - Day 2 - JavaScript Iteration

### ISSUE THREAD

**Issue by gstark** [SheaParrott/assignments#16]
# JavaScript Iteration

## Objectives

After completing this assignment, you should be able to:

* Demonstrate an understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/js-iteration) to your own account.
2. Change into your projects directory:
3. Clone your repository: `git clone js-iteration`
4. Change into your project's directory: `cd js-iteration`
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor]
7. Start the test runner: `yarn test`
7. Open `src/functions.test.js` and work on functions until tests pass.
8. Commit and push your work to GitHub.
9. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by SheaParrott** [comment]
this was a tough one, i will definitely be going back to this to practice. 
https://github.com/SheaParrott/js-iteration

**Comment by gstark** [comment]
Good work!

See if you can use the function `some` for the challenge `someoneToLove`

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--978506c32fc72f81eabd7234e584cda7e38900af/giphy-6.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/71)**__
