### ISSUE TITLE
Week 05 - Day 3 - Thanksgiving Break Assignment

### ISSUE THREAD

**Issue by gstark** [SheaParrott/assignments#17]
# Choose one or more of the following:
- Try the [Javascript Koans](https://github.com/suncoast-devs/koans)
- Implement Blackjack in React
- Implement Tic-Tac-Toe in React
- Implement [this homework](https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/snowman/)
- Go through the free [Javascript 30](https://javascript30.com)

# Videos to Watch
- Watch this [amazing video](https://vimeo.com/36579366)

**Comment by SheaParrott** [comment]
Here is the completed Koans 

https://github.com/SheaParrott/koans

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3921363294f2f54e76ec6fe9deb21cb56ace25a8/giphy-11.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/76)**__
