### ISSUE TITLE
Week 06 - Day 2 - One List

### ISSUE THREAD

**Issue by gstark** [SheaParrott/assignments#19]
In this assignment, you'll build a classic todo manager.

Something like: [One List](https://one-list.ambetha.surge.sh)

## Objectives

- Reinforce component architecture in React
- Effective use props and state in React

## Requirements

We're going to build todo manager. The user should be able to:
- Add new todo items
- Mark todo items as complete
- Delete todo items

Read the [documentation](https://one-list-api.herokuapp.com)

### Explorer Mode

- [x] Allow a todo to be created
- [x] Mark a todo complete
- [x] Delete a todo item

### Adventure Mode

- [ ] Allow the text of a todo item to be changed

### Epic Mode

- [ ] Allow for multiple lists by allowing the user to specify the `access token`

**Comment by SheaParrott** [comment]
https://github.com/SheaParrott/one-list

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--395b5be9a8246c8cf018274388a5d5392825ae8e/giphy-2.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/67)**__

**Comment by SheaParrott** [comment]
love this one ahahaha!
