### ISSUE TITLE
Week 07 - Day 1 - React Practice

### ISSUE THREAD

**Issue by gstark** [SheaParrott/assignments#22]
In this assignment, you will practice your React skills

## Objectives

* Use components and props effectively in React
* Use React Router to create declarative navigation in your application

### Explorer Mode

- *READ* each of the following assignments and choose one that you feel will help you practice the most:
 - Add React Router to your `Choose your own API` homework
 - Redo `Cloudy With a Chance of Syntax Error` in React
 - Redo `Blackjack` in React
 - Redo `Roshambo` in React
 - Do [Pet Adoption](https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/pet-adoption/)
 - Do [Crypto Ticker](https://suncoast.io/handbook/curriculum/front-end/react-i/assignments/crypto-ticker) with React and React Router (to show the details of one currency)
 - Do [Party Like It's 1989](https://suncoast.io/handbook/curriculum/front-end/react-i/assignments/party-like-its-1989)
 - Implement a different `Choose your own API`

### Adventure Mode

- Choose another of the above and create a second app

**Comment by SheaParrott** [comment]
https://github.com/SheaParrott/inspirational-quotes

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bceeb145d881263a0f2f05f92594ddf64d6d8c0a/giphy-13.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/78)**__
