### ISSUE TITLE
Week 09 - Day 3 - Create a React App for your API

### ISSUE THREAD

**Issue by mdewey** [SheaParrott/assignments#30]
For this assignment, you should take your safari API that was already created, and create a simple react app that consumes that API. 

## Objectives

* Work with an API that you created

## Requirements

* Create a React app that consumes an API that you created

### Explorer Mode

* [x] Finish all the endpoints from the Safari API
* [x] Create a simple react app, that uses some css make it looks friendly. 
* [x] The react app should:  
    * [x] Display all animals the user has seen
    * [x] Display all animals seen in the `Jungle`
    * [x] Remove all animals that I have seen in the `Desert`. 
    * [x] Add all the `CountOfTimesSeen` and get a total number of animals seen
    * [x] Get the `CountOfTimesSeen` of `lions`, `tigers` and `bears`
    

### Adventure Mode

* [x] Work on your capstone's HTML, CSS and JS

### .NET 

Here are the interesting commands you will need for tonight's assignment

- To add Entity Framework to your project: 
``` 
 dotnet add package Microsoft.EntityFrameworkCore.Design --version 2.1.3

 dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL --version 2.1.2
 ```

 - To create your database:
 ```
 createdb <<DatabaseName>>
 ```

 - To create the DbContext
 ```
 dotnet ef dbcontext scaffold "server=localhost;database=<<DatabaseName>>" Npgsql.EntityFrameworkCore.PostgreSQL -c <<DatabaseName>>Context

```

- Add a migration:
```
 dotnet ef migrations add AddBaordGameTable
```

- Update your database
```
dotnet ef database update  
```

 - Documentation: [Dotnet EF CLI Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)

**Comment by SheaParrott** [comment]
https://github.com/SheaParrott/safari-vacation-frontend

**Comment by SheaParrott** [comment]
https://github.com/SheaParrott/safari-vacation-frontend
https://github.com/SheaParrott/safari-vacation-api

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74dc376b990fefa4b57db26c0337e9d122b96fd7/giphy-16.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/81)**__
