### ISSUE TITLE
Week 09 - Day 4 - Holiday Break

### ISSUE THREAD

**Issue by mdewey** [SheaParrott/assignments#31]
For this break, we not only want you to enjoy the season but also stay engaged with your journey. 

## Objectives

* Review a past lecture that you may not have fully grokked
* Work on the capstone

## Requirements

* Create a summary of a past lecture to help further understanding of a topic
* Have a good first push at your capstone project

### Explorer Mode

* [x] Pick a lecture to go back and create details notes about the lectures. They should be more detailed than a high-level summary but do not need to be a dictation of the lecture. These notes should be focused on the core concepts of the lecture. Tell your instructor which video before you leave on Thursday. 

These are the notes that were created from the Intro to Joins lectures 

[https://suncoast.io/handbook/curriculum/back-end/full-stack-i/lecture/sql/intro-to-joins/](https://suncoast.io/handbook/curriculum/back-end/full-stack-i/lecture/sql/intro-to-joins/)

This is a *really good* example, yours don't have this detail, but this a good target to hit

* [x] Work on your HTML & CSS for your capstone. Focus on looks, no so much on functionality. While working this, start mapping out what API endpoints and database tables you will need to support your UI.  

### Adventure Mode

* [ ] Watch any of the videos from [https://suncoast.io/handbook/resources/videos/](https://suncoast.io/handbook/resources/videos/)

### Epic Mode

* [ ] Enjoy the holiday break and get some needed R&R.

**Comment by SheaParrott** [comment]
i am thinking about either going through the react router video, ruby day 1 or 2, or MobX.

**Comment by mdewey** [comment]
Intro to Ruby is good

**Comment by SheaParrott** [comment]
okay, thank you

**Comment by SheaParrott** [comment]
Hey, I finally got this homework assignment. I created a Google document for this. I am not sure if this meets the requirement of the assignment. If I need to go in more detail or summarise this more, please let me know. Below is the URL for the document. Have a nice day!

https://docs.google.com/document/d/1Xm0WIkzfW-tbZNOysItLaGrmpVCfzGAPxASshWE4STI/edit?usp=sharing

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![You are amazing](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--00e75725277d89ae8fc756a00a086407d1e278db/amazing.gif)
> &ldquo;You are amazing&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/23)**__
