### ISSUE TITLE
Week 02 - Day 2 - Roshambo

### ISSUE THREAD

**Issue by gstark** [SheaParrott/assignments#6]
Create a simple Rock-Paper-Scissors game.

## Objectives

- Work with JavaScript and the DOM
- Practice conditional logic

## Requirements

Do not worry about CSS for explorer mode, only do as HTML to show the functionality.

### Background

See the wikipedia page about [Rock, Paper, Scissors](https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors)

### How to get started

- Get familiar with rock, paper, scissors if you haven't played before (or in a while)
- Draw out on paper/whiteboard/computer the rough design of your application
  - See _Explorer Mode_ for the UI requirements
- Start by placing all the HTML elements on the page
- Style the user interface
- Write out in English, ALL the steps the application needs to take
  - For example "When user one clicks on Rock, remember that user one chooses Rock"
- Start adding JavaScript to make your program to do the steps you described above

### Explorer Mode

- [x] As a user I should be able to see three buttons for each player.
- [x] As a user, I should be able to pick an option for each player.
- [x] As a user, after each player makes their selection, I should be told who won and the game should be over.

### Adventure Mode

- [ ] Create a `vs computer` mode, that picks a selection.
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice)
- [ ] Make your computer AI unbeatable
- [ ] Give the user a choice to player against the various computer levels or another player
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by SheaParrott** [comment]
explorer mode done. Struggling with background image sizing for mobile.

https://github.com/SheaParrott/roshambo

**Comment by gstark** [comment]
Shea, this is awesome! I'm returning it to you as I'd like you to fix up the styling some to make it easier to read. 

The font is *TINY* on my desktop and combined with the font choice and text shadow it is hard to read. Let's get that cleaned up a tiny bit and resubmit.

I'd also like you to revise your variable names.. Things like `POChoice` should be named `PlayerOneChoice` -- in places where you have abbreviated, go ahead and expand those abbreviations and see if the code isn't easier to read.

In some cases you may need to change the name of a variable or function.

For instance:

```js
  playerOneRock.addEventListener('click', PORock)
```

Could be changed to

```js
  playerOneRock.addEventListener('click', playerOneClickedRock)
```

See how the name gives the reader an idea of what that function does. "Oh, this function must be called whenever the 'Player One Clicks on the Rock'" -- making it much easier to read.

Try reading your code out load *as written* and you'll see the places where you need to expand.

Nicely done. Just clean up a few things and resubmit! (git add, git commit, git push, re-close the homework)

**Comment by SheaParrott** [comment]
changed some styling around. I have my heart set on this font to keep my theme. If there are more that needs to be fixed, no problem. 
names changed as well.

https://github.com/SheaParrott/roshambo

**Comment by gstark** [comment]
It is more readable now, thanks!

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
